# Generated by Django 6.0.3 on 2026-03-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iftar_tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iftartable',
            name='photo',
        ),
    ]
