# Generated by Django 6.0.3 on 2026-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftar_tables', '0002_remove_iftartable_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iftartable',
            name='governorate',
            field=models.CharField(choices=[('Cairo', 'القاهرة'), ('Giza', 'الجيزة'), ('Dakahlia', 'الدقهلية'), ('Damietta', 'دمياط'), ('Alexandria', 'الإسكندرية'), ('Sharkia', 'الشرقية'), ('Qalyubia', 'القليوبية'), ('Beheira', 'البحيرة'), ('Menofia', 'المنوفية'), ('Fayoum', 'الفيوم'), ('Minya', 'المنيا'), ('Asyut', 'أسيوط'), ('Sohag', 'سوهاج'), ('Beni Suef', 'بني سويف'), ('Red Sea', 'البحر الأحمر'), ('New Valley', 'الوادي الجديد'), ('Luxor', 'الأقصر'), ('Qena', 'قنا'), ('Aswan', 'أسوان'), ('Ismailia', 'الإسماعيلية'), ('Suez', 'السويس'), ('North Sinai', 'شمال سيناء'), ('South Sinai', 'جنوب سيناء')], max_length=20),
        ),
    ]
